### ISSUE TITLE
dateForColumn since1970

### ISSUE THREAD

**Issue by krzyzanowskim** [ccgus/fmdb#18]
Hi,

I deal with CoreDate sqlite where real data is from [NSDate dateWithTimeIntervalSinceReferenceDate:] intead of [NSDate dateWithTimeIntervalSince1970:]. Don't know if it's common, but this is how it work with CoreData Data columns.

**Comment by kdubb** [comment]
I've taken a stab at this using a runtime setting in PR #416.  I chose a runtime setting because it allows easier integration with library management (e.g. CocoaPods). It's implemented using NSObject selectors so shouldn't have any performance impact.

**Comment by robertmryan** [comment]
FWIW, I see the curious `dateWithTimeIntervalSince1970` behavior, too. It's too bad, because the 1970 date works great with SQLite `unixepoch` settings in their date functions (making it easy to display dates in other SQLite tools). This is more awkward with the 1 Jan 2001 reference date.

**Comment by kdubb** [comment]
I feel your pain but the errors are quite annoying once you're back in Cocoa. Since the problem appears to be one of precision, maybe a better solution is to do the math explicitly to convert between the UNIX and Cocoa epochs. We could then always use the dateWithTimeSinceReferenceDate. This would preserve backwards compatibility and SQLite date conformance. I'll investigate that idea as an alternative.
