### ISSUE TITLE
Unable to use 'id' with any va_arg use in iOS5 Beta 3

### ISSUE THREAD

**Issue by XmasRights** [ccgus/fmdb#23]
New XCode preview gives a " "Second argument to 'va_arg' is of non-POD type 'id' error. 

All 3 uses in FMDatabase.m

``` Objective-C

- (void)_extractSQL:(NSString *)sql argumentsList:(va_list)args intoString:(NSMutableString *)cleanedSQL arguments:(NSMutableArray *)arguments {

    NSUInteger length = [sql length];
    unichar last = '\0';
    for (NSUInteger i = 0; i < length; ++i) {
        id arg = nil;
        unichar current = [sql characterAtIndex:i];
        unichar add = current;
        if (last == '%') {
            switch (current) {
                case '@':
                    arg = va_arg(args, id); 
                    break;
                    ....
```

**Comment by phillyger** [comment]
Attempting to run app on an iPad Air simulator 8.2/8.3 (on device it works fine) and it crashes at 'arg = va_arg(args, id);' with a EXC_BAD_ACCESS exception on first call to FMDatabase. iPad 2 simulator 8.2/8.3 works fine. Looking at the the source code for FMDatabase.m in v2.5, the code appears to have remained unchanged since this original issue was opened. Any ideas as to what's causing this? Is this a 32-bit/64-bit related issue.

**Comment by ccgus** [comment]
@phillyger - try running with zombies on?  Maybe you're trying to use a bad object.

**Comment by phillyger** [comment]
@ccgus - Thanks for the response. I found that the issue was an integer value getting passed as a parameter to an <code>executeQueryWithFormat</code> call, which in turn, was using the incorrect percent modifiers (i.e. using '%@' (wrong) instead of a '%d' (right)). Seems to be working as expected now. Thanks.

**Comment by robertmryan** [comment]
@phillyger I'm surprised you didn't get a compile time warning "Format specifies type 'id' but the argument has type 'int'". We added the `NS_FORMAT_FUNCTION` qualifier to the declaration of `executeQueryWithFormat` in the header to ensure you'd get warnings about that. Hmm.

Regardless, I guess we can close this issue.
