### ISSUE TITLE
sqlite cannot commit,no transaction is active

### ISSUE THREAD

**Issue by bill666500** [ccgus/fmdb#374]
I used the following code ,but it dosen't work. And the xcode gave me the " Error calling sqlite3_step (1: cannot commit - no transaction is active) SQLITE_ERROR DB Query: commit transaction"
FMDatabaseQueue *queue = [FMDatabaseQueue databaseQueueWithPath:path];
 [queue inDatabase:^(FMDatabase *db) {
        //todo iOS sqlite cannot commit, no transaction is active
         DLog(@"result:%d",[db executeUpdate:updateSql]);
         [db commit];
     }];

**Comment by ccgus** [comment]
If you're going to commit, you need to start a transaction first.

**Comment by robertmryan** [comment]
No commit needed here as you have only one SQL statement. (SQLite will commit each SQL statement unless you begin a transaction and then commit it later.)

But if you wanted to use transactions (i.e. you had multiple SQL statements and wanted them committed together or rolled back together), you could either manually being a transaction and then commit them when done, or just use `inTransaction` rather than `inDatabase`.

But as Gus says, it makes no sense to commit a transaction without beginning one.

**Comment by bill666500** [comment]
https://github.com/robertmryan
https://github.com/ccgus
Thank U very much
