### ISSUE TITLE
Error inserting batch: callback requested query abort

### ISSUE THREAD

**Issue by qiulang** [ccgus/fmdb#428]
When using executeStatements: withResultBlock for query I always get "Error inserting batch: callback requested query abort". I did not figure out why and if I use executeQuery, it works just fine.

Although I got this warning the query did succeed.

**Comment by ccgus** [comment]
Can you make a reproducible case, using the technique described in the README?

**Comment by qiulang** [comment]
Hi it is reproducible every time in my case. I have wrote a simple iOS project to reproduce it. Let me know how to send it to you.

What I did was first create a sqlite file (using sqlite3 in terminal), add to project then just use it. I got that error message every time I use executeStatements:withResultBlock method

**Comment by qiulang** [comment]
OK I post in my FMDB mail list

**Comment by qiulang** [comment]
I hit this problem again and finally figure out why!
"If an sqlite3_exec() callback returns non-zero, the sqlite3_exec() routine returns SQLITE_ABORT without invoking the callback again and without running any subsequent SQL statements." https://www.sqlite.org/capi3ref.html#sqlite3_exec

While in my executeStatements:withResultBlock:  I return YES, which is 1

So to avoid the problem I suggest the following 2 changes:

1.  typedef void(^FMDBExecuteStatementsCallbackBlock)(NSDictionary *resultsDictionary); 
2. int FMDBExecuteBulkSQLCallback(void *theBlockAsVoid, int columns, char **values, char **names) {
   ...
   execCallbackBlock(dictionary);
    return 0;
}

**Comment by robertmryan** [comment]
Like you said, the [SQLite documentation](http://sqlite.org/c3ref/exec.html) says:

> If an `sqlite3_exec()` callback returns non-zero, the `sqlite3_exec()` routine returns `SQLITE_ABORT` without invoking the callback again and without running any subsequent SQL statements.

Or, as the [FMDB class references](http://ccgus.github.io/fmdb/html/Classes/FMDatabase.html#//api/name/executeStatements:withResultBlock:) says of this block parameter:

> ... Note, if you supply this block, it must return integer value, zero upon success (this would be a good opportunity to use `SQLITE_OK`), non-zero value upon failure (which will stop the bulk execution of the SQL).

---

So, let's talk about your proposed change. 

First, you say "better to let your block decide whether you want to stop or not". That's precisely what the existing implementation does. If your block returns zero it proceeds. If not, it stops. It's entirely under the control of the block. It's admittedly, not a very common pattern in Objective-C, but

- it's well documented; 
- the existing `int` return type is more consistent with the SQLite C API;
- it seems misleading to suggest that the current implementation doesn't allow the block to decide, because it does; and 
- we favor backward compatible changes, but any change here would not be backward compatible and hence would be a challenge to users of the current API; at best, any change here should be deferred to a major release.

Second, you suggest changing the block to have a `void` return type rather than an `int` return type. So, how do you propose that the block indicate that it should stop or not? Surely if you remove the `int` return type, you'd have to introduce some other mechanism. Options include

- the `BOOL *` pattern that we see in older Cocoa enumeration methods ... this seems a bit anachronistic given that Cocoa, itself, seems to be moving away from this convention in their new APIs;
- a callback parameter mechanism that you see in the `URLSessionDelegate` APIs ... this is a fairly contemporary pattern, though it seems a bit clumsy to have block parameter as a parameter to a callback block;
- change this to return `BOOL`, a `true` or `false` where `true` = "success", rather than `int` where `0` = "success ... this might be more consistent with the rest of the FMDB API, but seems like a likely headache for any existing users of this `executeStatements` API.

Personally, this is a pretty long-winded way of saying that I wouldn't advocate any change here, but lets see what @ccgus and the rest of the community think. But perhaps I'm missing some aspect of your proposed solution, because I'm quite frankly not getting how your proposed implementation would allow the block to choose to stop `executeStatements` like the current implementation does.

**Comment by qiulang** [comment]
OK, now I realize I didn't think it through. My proposed change is not good.
