### ISSUE TITLE
Support iOS 7

### ISSUE THREAD

**Issue by robertmryan** [ccgus/fmdb#455]
On StackOverflow, someone posted regarding problems using Cocoapods with iOS 7 target because it is not compatible with dynamic libraries. See http://stackoverflow.com/questions/34566704/how-do-i-get-fmdb-on-project-target-ios-7-1-below-8/34566874#34566874. I suggested the person build for FMDB <strike>2.5.2</strike> 2.5 for now. [I apparently neglected up to update podspec for 2.5.2, so we had to go back to 2.5.]

The question is how do we maintain Cocoapods support that predates iOS 8 dynamic libraries, while enjoying dynamic library support enjoyed in later OS versions (and required by Carthage, using FMDB in extensions, etc.)?

**Comment by ccgus** [comment]
We don't I guess, unless there's a super easy way to do this.

I don't use Ccooapods, so I have no way to verify that it works or does whatever it's supposed to do. However, FMDB was designed so that you can just copy in the source files to your project and start using it, without dynamic libraries needed. So I think that's a reasonable way to go if the various package managers won't work for someone.
