### ISSUE TITLE
Why FMDatabaseQueue use dispatch_sync, not semaphore?

### ISSUE THREAD

**Issue by vincentlong889** [ccgus/fmdb#464]
I want to know why FMDatabaseQueue use dispatch_sync to keep thread safe, not semaphore?

The Scene: I use FMDatabaseQueue's interfaces in dispatch_async block, it means that my task will move from concurrent queue to FMDatabaseQueue's serial queue.

Whether it will improve performance, if use lock, like: dispatch_semaphore to keep thread safe?

**Comment by ccgus** [comment]
It's to keep multiple threads accessing the database from stepping all over each other.

**Comment by robertmryan** [comment]
I would question your premise that using semaphores are a better way to achieve thread-safety. Semaphores aren't going to be any more efficient, and it takes a lot more work. Dispatch queues, on the other hand, are very well suited to this problem and are very efficient. 

If your app has lost performance because you have multiple threads contending for `FMDatabaseQueue`, shifting to different synchronization method (locks, `@synchronized` blocks, etc.) will not improve the performance.

If your app is blocking, you should refactor the code to reduce contention. For example, if you have a background thread doing updates to the database, figure out how to get in and out more quickly (e.g. use transactions which dramatically improve the speed of multiple updates; break up the updates into smaller portions, etc.).

If the refactoring of your code isn't apparent, I would suggest you post a question on [Stack Overflow](http://stackoverflow.com) showing what you're doing in the background thread that is causing this contention issue, and I'm sure you'll get people to advise you further there.

But, in short, semaphores are no "silver bullet" that will improve the performance. You should tackle the fundamental database contention issues.
