### ISSUE TITLE
"executeQueryWithFormat:" Can't Work.

### ISSUE THREAD

**Issue by Morningxxx** [ccgus/fmdb#479]
I can do things with "executeQuery:[NSString  stringWithFormat:]".
But the same query can't work on "executeQueryWithFormat:".

No wrong no warning, just no result came out

**Comment by robertmryan** [comment]
You have to give us an example SQL statement for us to advise you further. But `executeQueryWithFormat` does not behave the same as `executeQuery` with `stringWithFormat`. See the caveats and discussion of the difference in the [documentation for `executeQueryWithFormat`](http://ccgus.github.io/fmdb/html/Classes/FMDatabase.html#//api/name/executeQueryWithFormat:).

**Comment by Morningxxx** [comment]
I use the method in as "FMResultSet *resultSet = [_db executeQueryWithFormat:@"select name,age from t_student where name like %%%s%%; ",keyword.UTF8String];".
I'm not sure if it is because of using Chinese characters in the "keyword".

**Comment by Morningxxx** [comment]
I used the method as "FMResultSet *resultSet = [_db executeQueryWithFormat:@"select name,age from t_student where name like %%%s%%; ",keyword.UTF8String];".
And i'm not sure if it is because of using Chinese characters in the "keyword".

**Comment by robertmryan** [comment]
Correct, putting the wildcards inside the SQL statement like that isn't going to work with `executeQueryWithFormat`. I know it seems like it should, but it will just not work because it really isn't doing a `stringWithFormat`-style replacement. (We're contemplating/debating deprecating `executeQueryWithFormat` altogethre because of this confusion.) You have to include the `%` wildcard characters inside the value, but that's not how `executeQueryWithFormat` works. Thus, you're stuck doing `executeQuery`/`stringWithFormat`, like:

```objc
FMResultSet *resultSet = [_db executeQuery:@"select name, age from t_student where name like ?;", [NSString stringWithFormat: @"%%%@%%", keyword]];
```
