### ISSUE TITLE
My App Crash at 'FMDatabase close' where 'FMDatabase.m:197' sometimes

### ISSUE THREAD

**Issue by mutongs** [ccgus/fmdb#494]
How can I solve this problem?What caused this problem？Please Help me,Thanks!

**Comment by ccgus** [comment]
We need a reproducible case where this happens.

**Comment by mutongs** [comment]
Swift update:
 do{
            try dataManager.executeUpdate("delete from spinit where stId =?", values: [index])
        }catch let error as NSError{
            qzprint("Delete error",error.localizedDescription)
        }
        dataManager.close()
// var dataManager:FMDatabase!

**Comment by robertmryan** [comment]
We need a small reproducible example of the problem. I tried your code and it worked fine.

Frankly, `close` is a very, very unlikely place to have a crash, so I really suspect that there's something else going on. You'd crash at that line if the implicitly unwrapped optional `dataManager` was `nil` (but you reference it a few lines above, so that can't be it).

So, ideally we need the simplest possible code snippet that can be used to reproduce the problem. Or, at the very least, we need to see the full crash log. But I really think there's something else going on. I don't see how the `delete` statement would succeed and the `close` statement would crash. It doesn't seem possible.

For the sake of completeness, this is the code sample I tried:

```swift
let documents = try! NSFileManager.defaultManager().URLForDirectory(.DocumentDirectory, inDomain: .UserDomainMask, appropriateForURL: nil, create: false)
let fileURL = documents.URLByAppendingPathComponent("test.sqlite")
let _ = try? NSFileManager.defaultManager().removeItemAtURL(fileURL)

dataManager = FMDatabase(path: fileURL.path)

guard dataManager.open() else {
    print("unable to open database")
    return
}

var index: Int!

do {
    try dataManager.executeUpdate("create table spinit (stId integer primary key autoincrement, name text)", values: nil)
    try dataManager.executeUpdate("insert into spinit (name) values (?)", values: ["foo"])
    try dataManager.executeUpdate("insert into spinit (name) values (?)", values: ["bar"])
    index = Int(dataManager.lastInsertRowId())
} catch {
    print("create/insert error: \(error)")
}

do {
    try dataManager.executeUpdate("delete from spinit where stId =?", values: [index])
} catch let error as NSError {
    print("Delete error \(error.localizedDescription)")
}

dataManager.close()
```
