### ISSUE TITLE
why first call [FMResultSet next] very slow

### ISSUE THREAD

**Issue by redihd** [ccgus/fmdb#507]
This is my code 
![fmdb code](https://cloud.githubusercontent.com/assets/3083399/16189575/8bdd77ac-370d-11e6-897f-5638ef863de5.png)
    In dataBase I have about 30000 rows, after executeQuery the result has about 3000 records
![fmdb executequery](https://cloud.githubusercontent.com/assets/3083399/16189891/21efa5c0-370f-11e6-80ad-a93ca2f3badf.png)
    But when I Run the code in my iphone ,It takes about 5~6 seconds to get all the records I want。
    Before run  [rs next] 
![fmdb before](https://cloud.githubusercontent.com/assets/3083399/16190221/ce32d9be-3710-11e6-9f9c-55797e5241e3.png)
    In the code    while ([rs next]){}
![fmdb in](https://cloud.githubusercontent.com/assets/3083399/16190299/1d22ffe0-3711-11e6-9adf-66b80bfc68a2.png)
    it takes 6 seconds to log getSingelDataFromDb

**Comment by ccgus** [comment]
It's probably slow because SQLite is doing the query. You're going to have to optimize it, there's nothing FMDB can do about that.

**Comment by robertmryan** [comment]
Agreed. This is not a FMDB issue, but rather a SQLite issue. 

The problem is likely that `data` (or one of the other rows) contains some non-trivial amount of data. In my test, when `data` was a few bytes, the delay was inconsequential, but when it included anything more than that (e.g. just 1kb), it had a huge impact on the retrieval of the first row of data.

This SQL has to retrieve the whole chat table in memory in order to retrieve the first row, which would account for the delay. I'd suggest refactoring the subquery so that it's retrieving the bare amount of information (e.g. just some unique row identifier), and I think you'll find it's much more efficient. Even better, see if you can use the subquery pattern altogether.

But, like Gus said, this is a SQLite question, not a FMDB question, so this is much better suited for a forum like [Stack Overflow](http://stackoverflow.com) than here.

**Comment by redihd** [comment]
ok thanks~

**Comment by vandzi** [comment]
If this is query issue, why it's slow on first resultSet.next() and not on db.exectuteQuery? I would expect that after exectureQuery, data are loaded in resultset

**Comment by robertmryan** [comment]
@vandzi - The `executeQuery` only prepares the SQL ([`sqlite3_prepare_v2`](https://sqlite.org/c3ref/prepare.html)) and, optionally, binds values to the `?` in SQL (`sqlite3_bind_xxx`](https://sqlite.org/c3ref/bind_blob.html)), but doesn’t actually perform the SQL. Only when you call `next` (calling [`sqlite_step`](https://sqlite.org/c3ref/step.html)) is data retrieved. 

It’s just how SQLite works.
