### ISSUE TITLE
FMDB with SQLCipher is not submodule compatible

### ISSUE THREAD

**Issue by repl-ullas-ml** [ccgus/fmdb#508]
I am using FMDB as a submodule. I Also need the database encryption. Going by the implementation file

```
- (BOOL)setKeyWithData:(NSData *)keyData {
#ifdef SQLITE_HAS_CODEC
    if (!keyData) {
        return NO;
    }
   int rc = sqlite3_key(_db, [keyData bytes], (int)[keyData length]);
    return (rc == SQLITE_OK);
#else
    return NO;
#endif
}
```

Encryption/Decrytion requires following settings

1.Build Settings -> Preprocessor Macros-> SQLITE_HAS_CODEC=1
2.Build Settings -> "Other C Flags" —>DSQLITE_HAS_CODEC

Although setting this value in my project which contains FMDB as submodule(subproject), doesn’t have any effect i.e. key is not set.

However if this settings is changed in FMDB project which is a submodule , everything is all right.

There should be a way to override SQLITE_HAS_CODEC/DSQLITE_HAS_CODEC from the main project which include FMDB as submodule

**Comment by ccgus** [comment]
I guess I don't know what FMDB should be doing that it isn't already.

You're talking about a git submodule?

**Comment by repl-ullas-ml** [comment]
@ccgus Yes i was referring to git submodules. For whatever reason we haven't adopted cocoa pods yet instead adding our dependancies as submodules. We wanted to adopt FMDB to deal with encrypted database. 

To simply accomplish this FMDB mandates to set SQLITE_HAS_CODEC/DSQLITE_HAS_CODEC. However the way git submodule works is,it holds the commit and use whatever is present in the commit pointer. As far as my investigation goes SQLITE_HAS_CODEC/DSQLITE_HAS_CODEC is not set in FMDB project instead mandates anyone using the project to override these settings.

Is forcing SQLITE_HAS_CODEC/DSQLITE_HAS_CODEC which is needed by a FMDB submodule/subproject from a main project(Adopter) feasible?

If not , what are the other options to look at? Hope i articulated my question right:)

**Comment by billymeltdown** [comment]
@repl-ullas-ml Are you using the `fmdb.xcodeproj` file to include FMDB in your project? It links against the system SQLite, which would not contain the sqlite3_key symbol, causing a crash at runtimewhen called. You don't need to use that project file, you could include the FMDB sources into your project directly from your submodule, instead of trying to link against a framework target in the `fmdb.xcodeproj` file, which might simplify things. Then set -DSQLITE_HAS_CODEC in the Other C Flags for your project file. Having done that I don't think you also need to set it to 1 in a pre-processor macro.

You'll also need to link against [SQLCipher](https://github.com/sqlcipher/sqlcipher), as opposed to SQLite, in your project file. Have you done that already? There's some basic instructions for building and linking a `libsqlcipher.a` [over here](https://www.zetetic.net/sqlcipher/ios-tutorial/). Hope that helps!

**Comment by repl-ullas-ml** [comment]
@ccgus Thanks it worked. As opposed to adding as submodule and linking fmdb.xcodeproj, i took your recommendation to add it as a physical files in my project directly, and override the DSQLITE_HAS_CODEC from my project directly, and all seems okay.
