### ISSUE TITLE
rollback flag set error

### ISSUE THREAD

**Issue by JQHee** [ccgus/fmdb#562]
When I use dbQueue insert new data,  Cannot assign to property:'rollback' is a 'let' constant error

The code
##         FMDBDatabaseTool.sharedInstance.dbQueue.inTransaction { db, rollback in {
            rollback?.memory = true

        }

**Comment by robertmryan** [comment]
Yep, Swift is evolving quickly. It's now `pointee` rather than `memory`. I'll update the documentation accordingly.

E.g.

```swift
queue.inTransaction { db, rollback in
    do {
        try db!.executeUpdate("INSERT INTO myTable VALUES (?)", values: [1])
        try db!.executeUpdate("INSERT INTO myTable VALUES (?)", values: [2])
        try db!.executeUpdate("INSERT INTO myTable VALUES (?)", values: [3])
        
        if whoopsSomethingWrongHappened {
            rollback!.pointee = true
            return
        }
        
        try db!.executeUpdate("INSERT INTO myTable VALUES (?)", values: [4])
    } catch {
        rollback!.pointee = true
        print(error)
    }
}
```

**Comment by robertmryan** [comment]
By the way, @ccgus, I'd be inclined to audit FMDB for nullability so that Swift users are spared the silly unwrapping of the `db` and `rollback` optionals that never can be `nil`. These are implicitly unwrapped optionals (which in Swift 2.3, no unwrapping was necessary), but in Swift 3 we now have to unwrap them in closures. 

Frankly, I'd be inclined to go ahead and go through the entire API and audit for nullability (so that both Swift and Objective-C users can clearly see in which cases parameters are required and when they're not). To audit the whole API for nullability is tiresome, but very simple to do.

The nullability audit won't affect Objective-C users (short of providing useful warnings if they pass `nil` to methods that don't accept `nil`), but it will spare Swift users from dealing with optionals unnecessarily.

It does require some non-backward compatible changes for Swift users (it's minor, something we're very accustomed to going through as the language quickly evolves). If you think that FMDB 3 is forthcoming, we could fold it into that. If not, I'd make this nullability audit a separate release, FMDB 2.8. Or, if the FMDB 3 in not likely to released imminently, maybe we even FMDB 3 so it correlates logically, if artificially, with Swift 3). Or maybe we pick a few FMDB 3 features to fold into this release, but defer other big changes to FMDB 4. That way, we can focus on delivering something now and not fall into the trap of trying to make its scope so broad that it becomes a barrier to delivering anything (a la _The Mythical Man-Month_'s "second system effect").

Thoughts?

**Comment by ccgus** [comment]
FMDB 3 isn't happening anytime soon, so doing 2.8 with the nullability would be a good idea.

FMDB 3 doesn't have huge changes, just some API breaking things, so I don't think it's a second system problem- rather it's just finishing it and figuring out what goes into it.
