### ISSUE TITLE
code=7 out of memory after database was closed.

### ISSUE THREAD

**Issue by klein-artur** [ccgus/fmdb#571]
Hi, 

is it normal that I get `db.hadError() == true` and error code 7 after i already closed the database?
I close it and then I wan't to see if it had errors. 

What I expect is that it tells me that all was ok.

If I check `db.hadError()` before I close the db I get `false`.

I don't really know if I'm right, but this seems not to be expected behavior, right?

Thank you for your help!

**Comment by robertmryan** [comment]
Confusingly, SQLite's "out of memory" error is generally not a true memory error, but rather a result of trying to interact with a database that has been closed and the internal `sqlite*` pointer is `nil`. 

Check all of your open and close calls and make sure you're not trying to interact with the database after it is closed.

**Comment by robertmryan** [comment]
SQLite's "out of memory" error is invariably not a true memory error, but rather a result of trying to interact with a database that has been closed and the internal `sqlite3*` pointer is `nil`. This is very curious behavior, IMHO, but that's how SQLite works.

You are deliberately calling `hadError` after closing a database (i.e. after FMDB's internal `sqlite3*` pointer has been set to `nil`). So, yes, because FMDB is just a thin wrapper around SQLite, we expect it to return SQLite's curious "out of memory" error. And even if we decide to change this behavior, we'd be reluctant to change this because there are undoubtedly apps out there which are reliant upon the existing behavior, where FMDB faithfully reports SQLite's curious errors.
