### ISSUE TITLE
About close the database

### ISSUE THREAD

**Issue by Zhang1Peng** [ccgus/fmdb#583]
In "http://stackoverflow.com/questions/15720272/when-to-close-sqlite-database-using-fmdb",I see your answer,Do you have any new ideas about this problem？

**Comment by robertmryan** [comment]
I'm not Gus, but I think his counsel to leave the database open is still prudent. You avoid a lot of overhead and it is very safe. Just make sure to have it open only once at a time. And if you're going to interact from multiple threads, use `FMDatabaseQueue` instead of using `FMDatabase` directly.

Why do you ask?

**Comment by Zhang1Peng** [comment]
Thank you. I just want to ask :)
