### ISSUE TITLE
Only one table will be created

### ISSUE THREAD

**Issue by Myge91** [ccgus/fmdb#601]
Hello everybody,

I have a weird issue while creating tables with swift. Here is my code:

```
let sqlStmts: String =
                    "CREATE TABLE IF NOT EXISTS LOGIN (ID INTEGER PRIMARY KEY AUTOINCREMENT, userName TEXT, password TEXT, sessionId TEXT);" +
                    "CREATE TABLE IF NOT EXISTS UserNumbers (ID INTEGER PRIMARY KEY AUTOINCREMENT, userNumber TEXT, organisationId TEXT);" +
                    "CREATE TABLE IF NOT EXISTS InspectionWaterObject (ID INTEGER PRIMARY KEY AUTOINCREMENT, waterId TEXT, waterName TEXT, organisationName TEXT, organisationId TEXT);" +
                    "CREATE TABLE IF NOT EXISTS Inspections (ID INTEGER PRIMARY KEY AUTOINCREMENT, synced INTEGER, description TEXT, firstName TEXT, lastName TEXT , userNumber TEXT, waterId TEXT, inspectionTime INTEGER);" +
                    "CREATE TABLE IF NOT EXISTS Configuration (ID INTEGER PRIMARY KEY AUTOINCREMENT, version INTEGER);"
                if (db.open()) {
                    if !(self.db.executeStatements(sqlStmts)) {
                        print("Error: \(self.db.lastErrorMessage())")
                    }else {
                        print("table created")
                    }
                }  else {
                    print("Error: \(self.db.lastErrorMessage())")
                }
```

I have checked the available tables in the database with this code:
```
func listAllTables() throws -> [String] {
        self.db.open()
        do {
            defer {self.db.close()}
            let resultSet = try db.executeQuery("select name from SQLITE_MASTER ", values: nil)
            var entries: [String] = []
            while resultSet.next() {
                entries.append(resultSet.string(forColumn: "name")!)
            }
            return entries
        } catch {
            throw error
        }
    }
```

This is the code how I initialize the database:

```
var db: FMDatabase = FMDatabase()
    let VERSION = 1
    init() {
        let filemgr = FileManager.default
        let dirPaths = filemgr.urls(for: .documentDirectory, in: .userDomainMask)
        
        let databasePath = dirPaths[0].appendingPathComponent("my.db").path
        let exists = filemgr.fileExists(atPath: databasePath as String)
        print(databasePath)
        do {
            if !exists {
                self._createTables(databasePath: databasePath as String)
            } else if try self._getVersion() < self.VERSION {
                self._createTables(databasePath: databasePath as String)
            }
        } catch {
            print("\(error)")
        }
    }
```

The first thing I don't understand is that only the first table LOGIN will be created.

The second weird thing is that after I restarted the app (not new installed) the database is available but the one table LOGIN is not in the database anymore.
Does anyone know what I'm doing wrong? 
Google did not help

Regards

Jan

**Comment by robertmryan** [comment]
I ran your `executeStatements` code and it created all of the tables fine, so that's not the problem. 

Sure, I'd personally replace those `self.db` with just `db` for consistency's sake. I'd also not try doing `lastErrorMessage` if `open` failed (because `lastErrorMessage` only works with open databases).

I wonder if you might have a database without the tables sitting in your Documents folder. I'd try removing app from device and trying again.

Regarding "database is available the one table LOGIN is not in the database anymore", how are you determining this? I wonder if you're looking at the wrong database (bundle vs what's in Xcode vs what's in device's Documents folder). Bottom line, tables cannot just disappear. You are either looking at the wrong database, the database was deleted (and then when you opened it it again, SQLite creates blank database for you), or the table was explicitly deleted. But it can't just disappear on its own.

**Comment by Myge91** [comment]
Thanks for your help! My bug was that I haven't initialized the database with the path so just `var db: FMDatabase = FMDatabase()`. That was my mistake.
