### ISSUE TITLE
Not able to install 2.7.4

### ISSUE THREAD

**Issue by SarthakShah31** [ccgus/fmdb#622]
I have  2.7.2 pod version installed currently in my project(Objective C), and facing some issue while fetching column name from resultset .

I have query in which I have to use join query and for that using alias of tables. When i am going to fetch using column-name from result set, i am not able to get, after some trial, i got that i have to use alias.columnanme to get it worked.

eg query:-
```objc
sql = @"select q.formId, q.groupId, s.subOptionId, s.subOptionText, s.isDeleted from Questions q left join (select questionSpeciesId, questionId, speciesId from QuestionSpecies where isDeleted = 0) qs on q.questionId = qs.questionId left join Options o on o.questionId = q.questionId and o.isDeleted = 0 left join (select optionId, optionSpeciesId, speciesId from OptionSpecies os where isDeleted = 0) os on os.optionId = o.optionId left join SubOptions  s on o.optionId = s.optionId  and s.isDeleted = 0  where q.groupId = '%@' and (q.isDeleted = 0 or q.isDeleted is null) and (qs.questionSpeciesId IS NULL OR qs.speciesId = '%@') and (os.optionSpeciesId IS NULL OR os.speciesId = '%@')order by formId, groupId, orderNumber"

//Not working
var val = [rs stringForColumn:@"formId"];

//Working - should not be
var val = [rs stringForColumn:@"q.formId"];
```

I have tried to install new version 2.7.4, but not able to install.
pod 'FMDB', '~> 2.7.4'
also tried with
pod 'FMDB
Giving me error - * mistyped the name or version.

Same thing is working in XCode 8.3.2, but in XCode 9 is not working.
So please check that new version is available to download, as i want to update to resolve above issue.

Thanks!

**Comment by tejas-ardeshna** [comment]
Facing the same issue. Any solution?

**Comment by ccgus** [comment]
I think you can do 'select q.formId as formId' instead of just q.formId.
I'm not sure what's up with the CocoaPods stuff, I don't use it personally.

**Comment by SarthakShah31** [comment]
Thanks, @ccgus , but as i mentioned 'select q.formId ' is working fine in XCode8.3.2, same thing is not working in XCode9. 
My project is old & very big, so the way you are asking to make change is not a perfect solution.
Thanks mate.
Still waiting for help!!!

**Comment by ccgus** [comment]
It's probably a change in SQLite then.

**Comment by ccgus** [comment]
Also, why is giving the solution not workable? I mean… it's a fix, right?

**Comment by SarthakShah31** [comment]
Yes, It can be a fix, but as I mentioned, my project is very lengthy so I want some overall-fix instead of manually fix, that's why asking.

**Comment by robertmryan** [comment]
@SarthakShah31 

On your SQL column name issue, the this is SQLite behavior, and has nothing to do with FMDB. FMDB just uses `sqlite3_column_name` when retrieving results by column name, and when you have subselect statements like this SQL, it now prefixes the column names with the table name. There's nothing that we can do about that. You have to change your code to use `AS`, just like Gus said.

The `sqlite3_column` [documentation](http://sqlite.org/c3ref/column_name.html) says:

> The name of a result column is the value of the "AS" clause for that column, if there is an AS clause. If there is no AS clause then the name of the column is unspecified and may change from one release of SQLite to the next.

And, apparently, as the documentation has warned us might happen, this behavior has indeed changed in the latest version of SQLite. It's not an Xcode version problem. It's not a FMDB problem. It is a SQLite version issue.

---

Consider this SQLite code:

```objc
int rc = sqlite3_open([fileURL.path cStringUsingEncoding:NSUTF8StringEncoding], &db);
NSAssert(rc == SQLITE_OK, @"Unable to create db");

rc = sqlite3_exec(db, "create table foo (foo_id integer primary key autoincrement, foo_value text)", nil, nil, nil);
NSAssert(rc == SQLITE_OK, @"Unable to create foo (%ld) %s", (long) rc, sqlite3_errmsg(db));

rc = sqlite3_exec(db, "create table bar (bar_id integer primary key autoincrement, foo_id int, bar_value text)", nil, nil, nil);
NSAssert(rc == SQLITE_OK, @"Unable to create bar (%ld) %s", (long) rc, sqlite3_errmsg(db));

rc = sqlite3_exec(db, "insert into foo (foo_value) values ('foo1')", nil, nil, nil);
NSAssert(rc == SQLITE_OK, @"Unable to insert into foo (%ld) %s", (long) rc, sqlite3_errmsg(db));

int64_t fooId = sqlite3_last_insert_rowid(db);

NSString *sql = [NSString stringWithFormat:@"insert into bar(foo_id, bar_value) values (%lld, 'bar1')", fooId];

rc = sqlite3_exec(db, [sql cStringUsingEncoding:NSUTF8StringEncoding], nil, nil, nil);
NSAssert(rc == SQLITE_OK, @"Unable to insert into bar (%ld) %s", (long) rc, sqlite3_errmsg(db));

sqlite3_stmt *statement;
rc = sqlite3_prepare_v2(db, "select f.foo_id, f.foo_value, b.bar_value from foo f left join (select * from bar) b on f.foo_id = b.foo_id", -1, &statement, nil);
NSAssert(rc == SQLITE_OK, @"Unable to prepare select (%ld) %s", (long) rc, sqlite3_errmsg(db));

rc = sqlite3_step(statement);
NSAssert(rc == SQLITE_ROW, @"Unable to step (%ld) %s", (long) rc, sqlite3_errmsg(db));

const char *name1 = sqlite3_column_name(statement, 0);
const char *name2 = sqlite3_column_name(statement, 1);
const char *name3 = sqlite3_column_name(statement, 2);

NSLog(@"%s %s %s", name1, name2, name3);

sqlite3_finalize(statement);
sqlite3_close(db);
```

In iOS 10 simulator, this reports column names without table prefixes:

> 2017-11-05 22:41:48.435 MyApp[14202:4645812] foo_id foo_value bar_value

But iOS 11 simulator reports column names with table prefixes:

> 2017-11-05 22:58:53.931573-0800 MyApp[14243:4673964] f.foo_id f.foo_value b.bar_value

If you eliminate the subselect statements, the problem disappears. But, then again, in the absence of `AS` syntax, we're not guaranteed that they might change the behavior later anyway. The way to future-proof your code is to add the `AS` syntax. For now, you can theoretically get away with only worrying about SQL with subselect statements, but it would be prudent to do this in all SQL retrieving data from multiple tables.

---

Regarding the problem with installing the latest version of FMDB via Cocoapods, this is a result of a problem with SQLite Cipher library, that is preventing us from pushing the latest version of FMDB up to the Cocoapods Trunk. This issue, annoyingly, is completely unrelated to any of the changes that have transpired in FMDB since 2.7.2, but is an issue with Cocoapods lint and the SQLite Cipher library. Unfortunately, the fix to this is non-trivial (involves tracking down problems in the SQLite Cipher library) I've been slammed with a ton of work that has prevented me from tackling this yet.

**Comment by groue** [comment]
This change has been introduced in SQLite 3.19.0. It is present in SQLite 3.19.3 shipped with iOS 11. It has been reverted in SQLite 3.20.0.

For more information, see:

- Ticket: https://sqlite.org/src/info/de3403bf5ae5f72ed
- Mailing-list: http://mailinglists.sqlite.org/cgi-bin/mailman/private/sqlite-users/2017-July/073955.html
- SQLite 3.20.0 release notes: https://sqlite.org/changes.html#version_3_20_0

**Comment by robertmryan** [comment]
FYI, iOS 11.1 is still using SQLite version 3.19.3.

**Comment by SarthakShah31** [comment]
Thanks, @robertmryan  & @groue for your efforts. I am going to use AS in my query.
