### ISSUE TITLE
How to improve sqlite query by setting PRAGMA in FMDB

### ISSUE THREAD

**Issue by Amitmundra** [ccgus/fmdb#625]
Hi ALl,
My query execution is taking too much time evan table has no data.
what should i do to improve sql query performance?
By setting PRAGMA, Can we improve query execution time?
Where can i set PRAGMA in FMDB?

If i set below PRAGMA then, Will it improve performance of query?
PRAGMA main.page_size = 4096;
PRAGMA main.cache_size=10000;
PRAGMA main.locking_mode=EXCLUSIVE;
PRAGMA main.synchronous=NORMAL;
PRAGMA main.journal_mode=WAL;
PRAGMA main.cache_size=5000;

Thanks.

**Comment by ccgus** [comment]
FMDB wraps SQLite, so you should look up optimization strategies for SQLite.

**Comment by Amitmundra** [comment]
Thanks ccgus, May you share any topic that may help to improve performance?

Is there any setting in FMDB before or after making sqlite connection?

**Comment by robertmryan** [comment]
This question seems better suited for sites like [Stack Overflow](https://stackoverflow.com). And when you do that, I'd suggest you include (a) what evidence you have that the problem is with some `PRAGMA` as opposed to something more fundamental; and (b) provide a [reproducible example of the problem](https://stackoverflow.com/help/mcve), because if you don't show people how to manifest the behavior you describe, they won't be able to help you.

But it seems exceedingly unlikely that FMDB is the source of your problem.

**Comment by robertmryan** [comment]
@Amitmundra - Before you post on [Stack Overflow](http://stackoverflow.com), I'd suggest you review their guidelines on [how to ask a good question](https://stackoverflow.com/help/how-to-ask).
