### ISSUE TITLE
SeekGuidance

### ISSUE THREAD

**Issue by flyOfYW** [ccgus/fmdb#734]
FMDB can get the corresponding type of column field of a table

**Comment by flyOfYW** [comment]
I looked at the class of FMResultSet and found sqlite3_column_type, but why didn't you develop this method, because you can't get the type of a column name, if
- (int) columnTypeIndex columnIdx {: (int)
Return sqlite3_column_type ([_statement statement], columnIdx);
} is ok, whether to provide such a similar method later, I currently use FMResultSet classification to expand

**Comment by ccgus** [comment]
I believe there's a pragma to get the type of a column:
https://stackoverflow.com/questions/11753871/getting-the-type-of-a-column-in-sqlite

**Comment by robertmryan** [comment]
@ccgus FWIW, I might be wary about relying on the schema because IIRC SQLite doesn’t enforce column types.

@flyOfYW I’d suggest using [`objectForColumnIndex`](http://ccgus.github.io/fmdb/html/Classes/FMResultSet.html#//api/name/objectForColumnIndex), which determines the type for the column and returns the appropriate object type. That’s probably better than littering your code with SQLite’s internal coding system for column types.
