### ISSUE TITLE
FMDB.podspec of tag 2.7.10 declares wrong version

### ISSUE THREAD

**Issue by wmathurin** [ccgus/fmdb#865]
The spec for tag 2.7.10 declares version 2.7.9
See: https://github.com/ccgus/fmdb/blob/2.7.10/FMDB.podspec

**Comment by alwayswith** [comment]
same here

**Comment by ccgus** [comment]
This is now fixed. Thanks!

**Comment by tiwoc** [comment]
That was a quick fix, I appreciate it 😎

It looks like it broke SPM though because SPM (and CocoaPods too, AFAIR) expect release tags to not change retroactively, but the 2.7.10 tag was moved to a different commit. This breaks SPM package version resolution with the following error message:

![Screenshot 2024-04-03 at 09 15 53](https://github.com/ccgus/fmdb/assets/1260821/63923a51-6023-4dca-aba8-fcac1bbd9847)

I was able to recover from this error by deleting `~/Library/Developer/Xcode/DerivedData/*`, `~/Library/Caches/org.swift.swiftpm`, and `~/Library/org.swift.swiftpm*`.

The best practice for fixing issues in a release (here: 2.7.10) would be following it up with a fixed version (2.7.11) instead of changing the release retroactively. I think this can still be done so that people who haven't upgraded to 2.7.10 yet won't run into the same issue, and to make recovery easier for people who are already on 2.7.10.

Anyhow, thanks for all your work on FMDB, we've been making good use of it for years now 🙂
